server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/indal_db
    username: indal_user
    password: indal_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always